[project]
name = "olyv"
version = "0.1.0"
description = "Quicken Development"
authors = [
    { name = "Christian Who Codes", email = "developer@christianwhocodes.space" },
]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "django>=5.2.7",
    "django-browser-reload>=1.21.0",
    "django-ckeditor-5>=0.2.18",
    "django-compressor>=4.5.1",
    "django-phonenumber-field[phonenumberslite]>=8.2.0",
    "django-sass-processor>=1.4.2",
    "django-split-settings>=1.3.2",
    "djangorestframework>=3.16.1",
    "libsass>=0.23.0",
    "pillow>=11.3.0",
    "tzdata>=2025.2",
]

[dependency-groups]
dev = ["djlint>=1.36.4", "ruff>=0.13.3"]

[project.urls]
Homepage = "https://github.com/christianwhocodes/olyv"
Repository = "https://github.com/christianwhocodes/olyv"
Issues = "https://github.com/christianwhocodes/olyv/issues"

[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"

[tool.djlint]
format_css = true
ignore = "H006,H016,H021,H023,H030,H031,T002"
blank_line_before_tag = "if,block,for"
blank_line_after_tag = "load,endif,endblock,endfor"

[tool.djlint.css]
indent_size = 2

[tool.ruff]
line-length = 101
