[project]
name = "olyv"
version = "0.1.0"
description = "Quicken Development"
authors = [
    { name = "christianwhocodes", email = "dev@christianwhocodes.space" },
]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.13,<4.0"

dependencies = [
    "tzdata (>=2025.2,<2026.0)",
    "django-browser-reload (>=1.18.0,<2.0.0)",
    "pillow (>=11.3.0,<12.0.0)",
    "django (>=5.2.5,<6.0.0)",
    "django-split-settings (>=1.3.2,<2.0.0)",
    "libsass (>=0.23.0,<0.24.0)",
    "django-sass-processor (>=1.4.2,<2.0.0)",
    "django-compressor (>=4.5.1,<5.0.0)",
    "djangorestframework (>=3.16.1,<4.0.0)",
    "django-phonenumber-field[phonenumberslite] (>=8.1.0,<9.0.0)",
    "django-ckeditor-5 (>=0.2.18,<0.3.0)",
]

[tool.poetry.group.dev.dependencies]
djlint = "^1.36.4"

[tool.djlint]
format_css = true
ignore = "H006,H016,H021,H023,H030,H031,T002"
blank_line_before_tag = "if,block,for"
blank_line_after_tag = "load,endif,endblock,endfor"

[tool.djlint.css]
indent_size = 2

[tool.ruff]
line-length = 101

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
